- name: Download Hasiicorp file in URL
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install Vault
  ansible.builtin.dnf:
    name: vault
    state: installed

- name: Copy HCL changed file
  ansible.builtin.template:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl

- name: start vault service
  ansible.builtin.systemd_service:
    name: vault
    state: restarted